### ISSUE TITLE
List of battlecup bugs

### ISSUE THREAD

**Issue by commentator24** [ValveSoftware/Dota2-Gameplay#14131]
Thumbs up appreciated 👍 

- [ ] trophy icon too high #14129
- [ ] trophy icon not showing on friend list? miniprofile used to have golden border too? but it no longer shows #12421
- [ ] dotaplus shard reward log display code instead of description #13452
- [ ] switching region does not turn off radio buttons #7976
- [ ] battlecup winner also incorrect sometimes #7976
- [ ] clicking battlecup tab after participation incorrectly show matchmaking prevented until thursday #9774 #7669
- [ ] cannot enter battlecup as official team? in the past a checkbox to queue rank as team. would be nice if this is available for battlecup to simplify it. even better if can queue as guild as well
- [ ] unable to find semifinal need rework #9175
Suggestion:
Lose quarterfinal = participation 500-1000 shards. e.g. 500 forfeit right away, 1000 if throne destroyed.
Win quarterfinal + cant find = 2500-5000 shards + trophy win OR auto find grand final opponents. please no refund.. only refund if coordinator down or minimum players not met regionally...
Win semifinal + can't find = 5000-7000 shards + trophy win? 7000 because usually distribution is 36% less than grand prize.
Win grandfinal = 20000 shards + trophy win as usual.
