### ISSUE TITLE
[MEGA Thread] MOST of Dota+ Relics do not work (in turbo?).

### ISSUE THREAD

**Issue by Aluerie** [ValveSoftware/Dota2-Gameplay#8899]
There exist a lot of open posts about Dota+ Relics. Currently, the bug tracker is rather a chaotic place thus, formatting-wise, it's better to gather all these issues into a **mega thread**. Maybe, it is a systematic bug as well.

> **Note**
> Please, all active folks, reference this issue for new relics related issues or mention already existing ones here. 

> **Note**
> Or just go ahead, play some games on same hero, test some relics, comment and:
> * Name those broken relics
> * Name game mode (Turbo/Non-Turbo) 
> * (preferably) Screenshot 
>   * your relics before a game(-s) - you can hold `Alt` to see numbers instead of levels.
>   * postgame(-s) relics progress
>   * relics alt-state after the game(-s)
> Friendly advice: please, combine these images in Paint or something into a singular (!) *wide* image instead of sending 3 images in one message because GitHub Markdown doesn't format those well.
> * (if possibly) a proof that you did the condition that didn't count i.e., screenshot for double shackleshot for corresponding relic. 

> **Warning**
> Don't forget to upvote this post (and other important posts) with "👍" for more priority from Valve devs.

It's hard to classify all already reported cases between game modes and check if the relics conditions were actually met because people reports are often ambiguous. So, this is why I would put a question mark to some of referenced issues below. And the lists are _**for sure far from being complete**_. 

## Table of Content: 
* Compilation of broken Relics (non-Turbo mode)
* Compilation of broken Relics (game mode isn't mentioned)
* Compilation of broken Relics (looks like only-Turbo)
* Compilation of Outdated Relics
* Compilation of Relics that do not make sense
* EXTRA REQUESTS 
* ❗ Some consensuses/speculations.

## Compilation of broken Relics (non-Turbo mode)
- [x] Oracle (Fate Edict) #9007 #8793 - this one is broken after 7.33
- [ ] Sven #7074
- [ ] Void Spirit #8820

## Compilation of broken Relics (game mode isn't mentioned)
- [ ] Anti-Mage #6292
- [ ] Crystal Maiden #5984
- [ ] Enchantress #7990
- [ ] Naga Siren #5364
- [ ] Rubick #6644
- [ ] Shadow Demon #6803
- [ ] Techies #6292

## Compilation of broken Relics (looks like only-Turbo)
- [x] Axe https://github.com/ValveSoftware/Dota2-Gameplay/issues/8899#issuecomment-1577782951
- [ ] Clinkz #5789
- [ ] Crystal Maiden https://github.com/ValveSoftware/Dota2-Gameplay/issues/8899#issuecomment-1569855109
- [ ] Dazzle #5918
- [ ] Drow Ranger #9275 https://github.com/ValveSoftware/Dota2-Gameplay/issues/7584#issuecomment-1473975606
- [x] Earthshaker #9667
- [x] Earth Spirit #9669 
- [ ] Enigma #7862
- [ ] Faceless Void #7889
- [ ] Hoodwink #7370 #5712 https://github.com/ValveSoftware/Dota2-Gameplay/issues/8899#issuecomment-1569680305
- [ ] Invoker #8858
- [ ] Juggernaut #6683 #6309 #5712
- [ ] Legion Commander #6991 #9161
- [ ] Marci #6035
- [ ] Mars https://github.com/ValveSoftware/Dota2-Gameplay/issues/8899#issuecomment-1604072779
- [ ] Mirana #6274
- [x] Muerta #8839
- [ ] Nightstalker #7500
- [x] Phoenix #9816
- [ ] Primal Beast #7153
- [ ] Pudge #9134
- [ ] Rubick #9887
- [ ] Sand King #6782 
- [x] Silencer #9804
- [ ] Shadow Shaman #6782
- [ ] SkyMage #5466
- [ ] Sniper #5586
- [ ] Troll #5752
- [ ] Viper #6782
- [x] Windranger #7955 https://github.com/ValveSoftware/Dota2-Gameplay/issues/8899#issuecomment-1569680305
- [ ] Witch Doctor #7584 #7148
- [ ] Underlord #9849
- [ ] Undying #6857

## Compilation of Outdated Relics
- [ ] Clinkz (Searing Arrows) #8838
- [ ] Venomancer (Poison Nova) - not sure how "Nova Gale Combos" relic works/fits anymore
- [ ] Marci - Dispose Multi Hero Stun - at least name is wrong 
- [ ] Dazzle - Bad Juju #9034
- [ ] Arc Warden spell relics do not track Dire version.

## Compilation of Relics that do not make sense

* Another major complaint from community is item relics. They simply lose their meaning when meta changes because nobody will/should buy them. 
- [ ] Morph Eblades combos
- [ ] Faceless Void Battle Fury Damage - one can argue that you shouldn't buy it ever. 
- [ ] Dust/Smokes/Wards relics on heroes that can be reworked/rethought by community into core. 
- [ ] Euls leading to kills often doesn't often make sense because people buy it for self protection in majority of cases (even if used offensively).
- [ ] a lot of questionable relics like the ones you can see being useful in some games, like Blade Mail Pudge, Pike Veno relics but one would also argue that these relics don't *belong* to them anymore. 

* There are also a lot of relics "3 man something" with ability that people rarely use/want to use on many people.
- [ ] Three hero rip tide Naga Siren (it would be cool if it counted this from multiple simultaneous Rip Tides)
- [ ] Cursed Crown Triple Stuns Dark Willow

## EXTRA REQUESTS 
- [x] It seems, there is no colour assigned to Universal heroes' relics. So, it looks strange: 
  * White/Gray colour of relics. Some people get confused that it means "disabled" relics. #9100 #8631.
  * Both Buy buttons are golden
  * Versus and "Entering battle as" screens look like it's all empty sockets. 
  * Please, give us Purple colour 🙏 
![Untitled](https://github.com/ValveSoftware/Dota2-Gameplay/assets/33165440/11ec8d36-fc39-4f98-ba17-e3d43c5428e5)

- [ ] Some heroes have 15/14 relics (#854) leading to some OCD tier pain. Please, refund those relics (or cut the number to 14/14) :D
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/33165440/faa3dc10-bf3b-4453-8c4c-e488a81ae5bd)

# ❗ Some consensuses/speculations.
* (?) Kill relics do not work for all heroes in turbo
* (?) Assists relics do not work for all heroes in turbo
* (?) Relics that are related to killing/assisting to kill other heroes do not work in turbo, i.e., "Powershot kills"
* The following one is probably the biggest help to fix it so in this ocean of todo-bullets I will use heading font:

# 🎯Diretide 2022 Update was the one that ruined relics in turbo

**Comment by Ran-00** [comment]
Turbo game: Quest finished ( so i silenced 2 or more enemy)
![239015258-3c301ebe-96d9-4d9a-ba5a-4d788307cbec](https://github.com/ValveSoftware/Dota2-Gameplay/assets/112323787/ea349ae8-a3d7-4ad1-874e-80f70514066e)

Here you can see it did not track (silenced enemies; multi hero silence)
![239015538-317f1376-3483-4855-bd56-de92e491ab18](https://github.com/ValveSoftware/Dota2-Gameplay/assets/112323787/30178e19-6228-4bf0-8399-2f2f6712a887)

Here you can see i own the relic
![239015617-ef1c3890-5f58-4525-bfcc-29f1ec2fd7f5](https://github.com/ValveSoftware/Dota2-Gameplay/assets/112323787/dbf60cd7-8285-427d-83ea-7f96f7ea338f)

Extra request: (also, removing the .5 at the end on the relics would make them look more aesthetically pleasing. have them count in turbo for half, but dont show .5, looks bad especially for relics with millions)

**Comment by Aluerie** [comment]
Well, haha. Not sure what it exactly means. 

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/33165440/8157fd36-2590-4bf4-ba8c-9883df8ccc53)

**Comment by Ran-00** [comment]
Played a turbo just to test : Didn't count Kills, Kill assists, enemies silenced, multi-hero silences.( drow ranger)

**Comment by kwanesir** [comment]
Tested CM in turbo after update - no change, only 3/10 common relics track, no kills, assists, etc...

**Comment by Andrispm01** [comment]
Are relics still grey for all universal heroes or have they fixed that bug on some heroes? (i play abaddon and on his page it still looks like unpurchased even tho im 14/14)

**Comment by suhasahin** [comment]
Some of Axe's relic not working on turbo. Call Damage Done, Battle Hunger Kills, Near Death kills, Enemies culled, call damage taken, triple kills, mega kill streaks, kill assists and kills not counting.

**Comment by Aluerie** [comment]
Colour is fixed. 
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/33165440/3479514e-e959-41b6-9ca9-cfdb1a37f35b)

**Comment by IDuckinfHatwU** [comment]
I don't know will it help or not, or it was mentioned before, but every single relic on every single hero that was bought before 1st September 2022 Battle Pass update is working in turbo
I had every single relic on void spirit and it counts half of the progress as it should, but for example if we look at Mars relics, most of them aren't working at all.
![Void Spirit](https://github.com/ValveSoftware/Dota2-Gameplay/assets/137499942/91508b05-4027-48c0-9625-f80bcd8ed7b3)
![Mars1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/137499942/dad42c8d-b8cf-4dbf-b0ab-f6d0627e56d8)
![Mars2](https://github.com/ValveSoftware/Dota2-Gameplay/assets/137499942/d1158338-2a8d-4ec3-935f-476631d54311)

**Comment by chrisf-valve** [comment]
All relics in turbo should now give half credit, please let me know if you find any going forward that specifically do not give credit in turbo.

**Comment by suhasahin** [comment]
> All relics in turbo should now give half credit, please let me know if you find any going forward that specifically do not give credit in turbo.

i can confirm that Axe's Relics are now working with half credit on turbo games. 

https://github.com/ValveSoftware/Dota2-Gameplay/issues/8899#issuecomment-1577782951

**Comment by Aluerie** [comment]
It's a been a few months. I think I'm confident about closing this issue because

* I played my ~25 heroes with 14/14 relics exclusively in turbo while tracking the progress and so far every single relic works fine. 
* People don't post new issues about broken relics

---
Meaning that the only remaining problem is outdated relics,  i.e.
* Clinkz - doesn't have Searing Arrows anymore and the relic doesn't seem count them from the Tar Bomb?
* Venomancer - Poison Nova Comboes doesn't work with new nova
* Marci - Dispose Multi Hero Stun works fine but name is wrong since it doesn't stun.
* Dazzle - Bad Juju been reworked but relic wasn't 
* Arc Warden spell relics do not track Dire version.
* More?

which probably needs to be posted separately, idk?
